name: Docker deploy

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Deploy
        run: |
          docker-compose down -v || exit
          docker-compose --env-file .env.production up --build -d || exit
