name: Main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: NPM Install and unit test
    uses: ./.github/workflows/job-build.yml

  deploy:
    name: Deploy and integration tests
    uses: ./.github/workflows/job-deploy.yml
    needs: install
    secrets:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

