name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: NPM Install and unit test
    uses: ./.github/workflows/job-install.yml

  docker-deploy:
    name: Docker deploy and integration tests
    uses: ./.github/workflows/job-deploy.yml
